module MoveCode
  JAB_LEFT = "JAB_LEFT"
  JAB_RIGHT = "JAB_RIGHT"
  LEFT_BODY_BLOW = "LEFT_BODY_BLOW"
  RIGHT_BODY_BLOW = "RIGHT_BODY_BLOW"
  DODGE_LEFT = "DODGE_LEFT"
  DODGE_RIGHT = "DODGE_RIGHT"
  DEFEND = "DEFEND"
  UPPERCUT = "UPPERCUT"
  ILLEGAL_MOVE = "ILLEGAL_MOVE"
end
