module MoveCode
  JAB_LEFT = "JAB_LEFT"
  JAB_RIGHT = "JAB_RIGHT"
  LEFT_BODY_BLOW = "LEFT_BODY_BLOW"
  RIGHT_BODY_BLOW = "RIGHT_BODY_BLOW"
  DODGE_LEFT = "DODGE_LEFT"
  DODGE_RIGHT = "DODGE_RIGHT"
  DEFEND = "DEFEND"
  DUCK = "DUCK"
  UPPERCUT = "UPPERCUT"
  ILLEGAL_MOVE = "ILLEGAL_MOVE"

  BASIC_ATTACKS = [MoveCode::JAB_LEFT, MoveCode::JAB_RIGHT, MoveCode::LEFT_BODY_BLOW, MoveCode::RIGHT_BODY_BLOW]
  EVASIVE_MOVES = [MoveCode::DODGE_LEFT, MoveCode::DODGE_RIGHT, MoveCode::DUCK]
end
