module MoveCode
  JAB_LEFT = "JAB_LEFT"
  JAB_RIGHT = "JAB_RIGHT"
  LEFT_BODY_BLOW = "LEFT_BODY_BLOW"
  RIGHT_BODY_BLOW = "RIGHT_BODY_BLOW"
  DODGE_LEFT = "DODGE_LEFT"
  DODGE_RIGHT = "DODGE_RIGHT"
  DEFEND = "DEFEND"
  DUCK = "DUCK"
  UPPERCUT = "UPPERCUT"
  ILLEGAL_MOVE = "ILLEGAL_MOVE"

  ALL_MOVES = [JAB_LEFT, JAB_RIGHT, LEFT_BODY_BLOW, RIGHT_BODY_BLOW, DODGE_LEFT, DODGE_RIGHT, DEFEND, DUCK, UPPERCUT, ILLEGAL_MOVE]
  BASIC_ATTACKS = [JAB_LEFT, JAB_RIGHT, LEFT_BODY_BLOW, RIGHT_BODY_BLOW]
  EVASIVE_MOVES = [DODGE_LEFT, DODGE_RIGHT, DUCK]
end
